#ifndef __D3D11_RENDER_DEF_H__
#define __D3D11_RENDER_DEF_H__

#include "RenderDef.h"


// TEXTURE_ADDRESS_MODE와 D3D11_TEXTURE_ADDRESS_MODE 매핑 테이블
static constexpr D3D11_TEXTURE_ADDRESS_MODE D3D11_IMPL_TEXTURE_ADDRESS_MODE[(int)TEXTURE_ADDRESS_MODE::EMAX] =
{
    D3D11_TEXTURE_ADDRESS_WRAP,
    D3D11_TEXTURE_ADDRESS_MIRROR,
    D3D11_TEXTURE_ADDRESS_CLAMP,
    D3D11_TEXTURE_ADDRESS_BORDER,
    D3D11_TEXTURE_ADDRESS_MIRROR_ONCE
};

// DEPTH_FUNC와 D3D11_COMPARISON_FUNC 매핑 테이블
static constexpr D3D11_COMPARISON_FUNC D3D11_IMPL_COMPARISON_FUNC[(int)COMPARISON_FUNC::EMAX] =
{
    D3D11_COMPARISON_NEVER,
    D3D11_COMPARISON_LESS,
    D3D11_COMPARISON_EQUAL,
    D3D11_COMPARISON_LESS_EQUAL,
    D3D11_COMPARISON_GREATER,
    D3D11_COMPARISON_NOT_EQUAL,
    D3D11_COMPARISON_GREATER_EQUAL,
    D3D11_COMPARISON_ALWAYS
};

// BLEND_FACTOR와 D3D11_BLEND 매핑 테이블
static constexpr D3D11_BLEND D3D11_IMPL_BLEND_FACTOR[(int)BLEND_FACTOR::EMAX] =
{
    D3D11_BLEND_ZERO,
    D3D11_BLEND_ONE,
    D3D11_BLEND_SRC_COLOR,
    D3D11_BLEND_INV_SRC_COLOR,
    D3D11_BLEND_SRC_ALPHA,
    D3D11_BLEND_INV_SRC_ALPHA,
    D3D11_BLEND_DEST_ALPHA,
    D3D11_BLEND_INV_DEST_ALPHA,
    D3D11_BLEND_DEST_COLOR,
    D3D11_BLEND_INV_DEST_COLOR,
    D3D11_BLEND_SRC_ALPHA_SAT,
    D3D11_BLEND_BLEND_FACTOR,
    D3D11_BLEND_INV_BLEND_FACTOR,
    D3D11_BLEND_SRC1_COLOR,
    D3D11_BLEND_INV_SRC1_COLOR,
    D3D11_BLEND_SRC1_ALPHA,
    D3D11_BLEND_INV_SRC1_ALPHA
};

// BLEND_OP와 D3D11_BLEND_OP 매핑 테이블
static constexpr D3D11_BLEND_OP D3D11_IMPL_BLEND_OP[(int)BLEND_OP::EMAX] =
{
    D3D11_BLEND_OP_ADD,
    D3D11_BLEND_OP_SUBTRACT,
    D3D11_BLEND_OP_REV_SUBTRACT,
    D3D11_BLEND_OP_MIN,
    D3D11_BLEND_OP_MAX
};

// COLOR_WRITE_MASK와 D3D11_COLOR_WRITE_ENABLE 매핑 테이블
static constexpr uint8_t D3D11_IMPL_COLOR_WRITE_MASK[MAX_COLOR_WRITE_MASK] =
{
	D3D11_COLOR_WRITE_ENABLE_RED,
	D3D11_COLOR_WRITE_ENABLE_GREEN,
	D3D11_COLOR_WRITE_ENABLE_BLUE,
	D3D11_COLOR_WRITE_ENABLE_ALPHA,
	D3D11_COLOR_WRITE_ENABLE_ALL
};

// FILL_MODE와 D3D11_FILL_MODE 매핑 테이블
static constexpr D3D11_FILL_MODE D3D11_IMPL_FILL_MODE[(int)FILL_MODE::EMAX] =
{
    D3D11_FILL_WIREFRAME,
    D3D11_FILL_SOLID
};

// CULL_MODE와 D3D11_CULL_MODE 매핑 테이블
static constexpr D3D11_CULL_MODE D3D11_IMPL_CULL_MODE[(int)CULL_MODE::EMAX] =
{
    D3D11_CULL_NONE,
    D3D11_CULL_FRONT,
    D3D11_CULL_BACK
};

// STENCIL_OP와 D3D11_STENCIL_OP 매핑 테이블
static constexpr D3D11_STENCIL_OP D3D11_IMPL_STENCIL_OP[(int)STENCIL_OP::EMAX] =
{
    D3D11_STENCIL_OP_KEEP,
    D3D11_STENCIL_OP_ZERO,
    D3D11_STENCIL_OP_REPLACE,
    D3D11_STENCIL_OP_INCR_SAT,
    D3D11_STENCIL_OP_DECR_SAT,
    D3D11_STENCIL_OP_INVERT,
    D3D11_STENCIL_OP_INCR,
    D3D11_STENCIL_OP_DECR
};

static constexpr D3D11_USAGE D3D11_IMPL_BUFFER_USAGE[(int)BUFFER_USAGE::EMAX] =
{
    D3D11_USAGE_DEFAULT,
    D3D11_USAGE_IMMUTABLE,
    D3D11_USAGE_DYNAMIC,
    D3D11_USAGE_STAGING
};

enum class D3D11_BUFFER_TYPE : uint8
{
    VERTEX_BUFFER,
    INDEX_BUFFER,
	CONSTANT_BUFFER
};

enum class D3D11_BUFFER_STRATEGY : uint8
{
	// 독립, 버퍼풀, 트랜지언트 버퍼
	INDEPENDENT,
    POOL,
	TRANSIENT
};

#define MAKE_BUFFER_POOL_ID(Format, Index) (((uint32_t)(Format) << 24) | ((uint32_t)(Index) & 0x00FFFFFF))
#define GET_BUFFER_POOL_FORMAT(PoolID) ((D3D11_BUFFER_TYPE)(((PoolID) >> 24) & 0xFF))
#define GET_BUFFER_POOL_INDEX(PoolID) ((uint32_t)((PoolID) & 0x00FFFFFF))

__FORCEINLINE D3D11_FILTER __D3D11ConvSamplerFilter(
    SAMPLER_FILTER MinFilter,
    SAMPLER_FILTER MagFilter,
    SAMPLER_FILTER MipFilter,
    uint8_t MaxAnisotropy
)
{
    // Anisotropic 필터링이 활성화된 경우
    if (MaxAnisotropy > 1)
    {
        return D3D11_FILTER_ANISOTROPIC;
    }

    // NONE 처리 - 기본값을 LINEAR로 설정
    if (MinFilter == SAMPLER_FILTER::NONE)
        MinFilter = SAMPLER_FILTER::LINEAR;
    if (MagFilter == SAMPLER_FILTER::NONE)
        MagFilter = SAMPLER_FILTER::LINEAR;
    if (MipFilter == SAMPLER_FILTER::NONE)
        MipFilter = SAMPLER_FILTER::LINEAR;

    // 모든 조합을 명시적으로 처리
    // NEAREST = POINT, LINEAR = LINEAR

    // Min=NEAREST, Mag=NEAREST, Mip=NEAREST
    if (MinFilter == SAMPLER_FILTER::NEAREST &&
        MagFilter == SAMPLER_FILTER::NEAREST &&
        MipFilter == SAMPLER_FILTER::NEAREST)
    {
        return D3D11_FILTER_MIN_MAG_MIP_POINT;
    }

    // Min=NEAREST, Mag=NEAREST, Mip=LINEAR
    if (MinFilter == SAMPLER_FILTER::NEAREST &&
        MagFilter == SAMPLER_FILTER::NEAREST &&
        MipFilter == SAMPLER_FILTER::LINEAR)
    {
        return D3D11_FILTER_MIN_MAG_POINT_MIP_LINEAR;
    }

    // Min=NEAREST, Mag=LINEAR, Mip=NEAREST
    if (MinFilter == SAMPLER_FILTER::NEAREST &&
        MagFilter == SAMPLER_FILTER::LINEAR &&
        MipFilter == SAMPLER_FILTER::NEAREST)
    {
        return D3D11_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT;
    }

    // Min=NEAREST, Mag=LINEAR, Mip=LINEAR
    if (MinFilter == SAMPLER_FILTER::NEAREST &&
        MagFilter == SAMPLER_FILTER::LINEAR &&
        MipFilter == SAMPLER_FILTER::LINEAR)
    {
        return D3D11_FILTER_MIN_POINT_MAG_MIP_LINEAR;
    }

    // Min=LINEAR, Mag=NEAREST, Mip=NEAREST
    if (MinFilter == SAMPLER_FILTER::LINEAR &&
        MagFilter == SAMPLER_FILTER::NEAREST &&
        MipFilter == SAMPLER_FILTER::NEAREST)
    {
        return D3D11_FILTER_MIN_LINEAR_MAG_MIP_POINT;
    }

    // Min=LINEAR, Mag=NEAREST, Mip=LINEAR
    if (MinFilter == SAMPLER_FILTER::LINEAR &&
        MagFilter == SAMPLER_FILTER::NEAREST &&
        MipFilter == SAMPLER_FILTER::LINEAR)
    {
        return D3D11_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR;
    }

    // Min=LINEAR, Mag=LINEAR, Mip=NEAREST
    if (MinFilter == SAMPLER_FILTER::LINEAR &&
        MagFilter == SAMPLER_FILTER::LINEAR &&
        MipFilter == SAMPLER_FILTER::NEAREST)
    {
        return D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT;
    }

    // Min=LINEAR, Mag=LINEAR, Mip=LINEAR
    if (MinFilter == SAMPLER_FILTER::LINEAR &&
        MagFilter == SAMPLER_FILTER::LINEAR &&
        MipFilter == SAMPLER_FILTER::LINEAR)
    {
        return D3D11_FILTER_MIN_MAG_MIP_LINEAR;
    }

    // 기본값 (도달하면 안 됨)
    assert(false && "Invalid filter combination");
    return D3D11_FILTER_MIN_MAG_MIP_LINEAR;
}

// Border Color를 FLOAT[4] 배열로 변환
__FORCEINLINE void __D3D11ConvBorderColor(BORDER_COLOR BorderColor, const FLOAT4* pCustomBorderColor, FLOAT* pOut)
{
    assert(pOut != nullptr && "pOut cannot be null");

    if (BorderColor == BORDER_COLOR::TRANSPARENT_BLACK)
    {
        pOut[0] = 0.0f;  // R
        pOut[1] = 0.0f;  // G
        pOut[2] = 0.0f;  // B
        pOut[3] = 0.0f;  // A
    }
    else if (BorderColor == BORDER_COLOR::OPAQUE_BLACK)
    {
        pOut[0] = 0.0f;  // R
        pOut[1] = 0.0f;  // G
        pOut[2] = 0.0f;  // B
        pOut[3] = 1.0f;  // A
    }
    else if (BorderColor == BORDER_COLOR::OPAQUE_WHITE)
    {
        pOut[0] = 1.0f;  // R
        pOut[1] = 1.0f;  // G
        pOut[2] = 1.0f;  // B
        pOut[3] = 1.0f;  // A
    }
    else if (BorderColor == BORDER_COLOR::CUSTOM)
    {
        // CUSTOM의 경우 호출자가 직접 설정해야 함
        // 기본값으로 Transparent Black 설정
        if (pCustomBorderColor)
        {
			pOut[0] = pCustomBorderColor->x;
            pOut[1] = pCustomBorderColor->y;
            pOut[2] = pCustomBorderColor->z;
			pOut[3] = pCustomBorderColor->w;
        }
        else
        {
            pOut[0] = 0.0f;
            pOut[1] = 0.0f;
            pOut[2] = 0.0f;
            pOut[3] = 0.0f;
        }
    }
    else
    {
        pOut[0] = 0.0f;
        pOut[1] = 0.0f;
        pOut[2] = 0.0f;
        pOut[3] = 0.0f;
    }
}

/*
// DEPTH_WRITE_MASK와 D3D11_DEPTH_WRITE_MASK 매핑 테이블
static constexpr D3D11_DEPTH_WRITE_MASK D3D11_IMPL_DEPTH_WRITE_MASK[(int)DEPTH_WRITE_MASK::EMAX] =
{
    D3D11_DEPTH_WRITE_MASK_ZERO,
    D3D11_DEPTH_WRITE_MASK_ALL
};



// STENCIL_OP와 D3D11_STENCIL_OP 매핑 테이블
static constexpr D3D11_STENCIL_OP D3D11_IMPL_STENCIL_OP[(int)STENCIL_OP::EMAX] =
{
    D3D11_STENCIL_OP_KEEP,
    D3D11_STENCIL_OP_ZERO,
    D3D11_STENCIL_OP_REPLACE,
    D3D11_STENCIL_OP_INCR_SAT,
    D3D11_STENCIL_OP_DECR_SAT,
    D3D11_STENCIL_OP_INVERT,
    D3D11_STENCIL_OP_INCR,
    D3D11_STENCIL_OP_DECR
};






// COMPARISON_FUNC와 D3D11_COMPARISON_FUNC 매핑 테이블
static constexpr D3D11_COMPARISON_FUNC D3D11_IMPL_COMPARISON_FUNC[(int)COMPARISON_FUNC::EMAX] =
{
    D3D11_COMPARISON_NEVER,
    D3D11_COMPARISON_LESS,
    D3D11_COMPARISON_EQUAL,
    D3D11_COMPARISON_LESS_EQUAL,
    D3D11_COMPARISON_GREATER,
    D3D11_COMPARISON_NOT_EQUAL,
    D3D11_COMPARISON_GREATER_EQUAL,
    D3D11_COMPARISON_ALWAYS
};

// FILTER_TYPE와 D3D11_FILTER 매핑 테이블
static constexpr D3D11_FILTER D3D11_IMPL_FILTER[(int)18] =
{
    D3D11_FILTER_MIN_MAG_MIP_POINT,
    D3D11_FILTER_MIN_MAG_POINT_MIP_LINEAR,
    D3D11_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT,
    D3D11_FILTER_MIN_POINT_MAG_MIP_LINEAR,

    D3D11_FILTER_MIN_LINEAR_MAG_MIP_POINT,
    D3D11_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR,
    D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT,
    D3D11_FILTER_MIN_MAG_MIP_LINEAR,

    D3D11_FILTER_ANISOTROPIC,
    D3D11_FILTER_COMPARISON_MIN_MAG_MIP_POINT,
    D3D11_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR,
    D3D11_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT,

    D3D11_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR,
    D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT,
    D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR,
    D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT,

    D3D11_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR,
    D3D11_FILTER_COMPARISON_ANISOTROPIC
};

//
*/

// COLOR_FORMAT와 DXGI_FORMAT 매핑 테이블
static constexpr DXGI_FORMAT D3D11_IMPL_COLOR_FORMAT[(int)COLOR_FORMAT::EMAX] =
{
    DXGI_FORMAT_UNKNOWN,
    DXGI_FORMAT_R32G32B32A32_TYPELESS,
    DXGI_FORMAT_R32G32B32A32_FLOAT,
    DXGI_FORMAT_R32G32B32A32_UINT,
    DXGI_FORMAT_R32G32B32A32_SINT,
    DXGI_FORMAT_R32G32B32_TYPELESS,
    DXGI_FORMAT_R32G32B32_FLOAT,
    DXGI_FORMAT_R32G32B32_UINT,
    DXGI_FORMAT_R32G32B32_SINT,
    DXGI_FORMAT_R16G16B16A16_TYPELESS,
    DXGI_FORMAT_R16G16B16A16_FLOAT,
    DXGI_FORMAT_R16G16B16A16_UNORM,
    DXGI_FORMAT_R16G16B16A16_UINT,
    DXGI_FORMAT_R16G16B16A16_SNORM,
    DXGI_FORMAT_R16G16B16A16_SINT,
    DXGI_FORMAT_R32G32_TYPELESS,
    DXGI_FORMAT_R32G32_FLOAT,
    DXGI_FORMAT_R32G32_UINT,
    DXGI_FORMAT_R32G32_SINT,
    DXGI_FORMAT_R32G8X24_TYPELESS,
    DXGI_FORMAT_D32_FLOAT_S8X24_UINT,
    DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS,
    DXGI_FORMAT_X32_TYPELESS_G8X24_UINT,
    DXGI_FORMAT_R10G10B10A2_TYPELESS,
    DXGI_FORMAT_R10G10B10A2_UNORM,
    DXGI_FORMAT_R10G10B10A2_UINT,
    DXGI_FORMAT_R11G11B10_FLOAT,
    DXGI_FORMAT_R8G8B8A8_TYPELESS,
    DXGI_FORMAT_R8G8B8A8_UNORM,
    DXGI_FORMAT_R8G8B8A8_UNORM_SRGB,
    DXGI_FORMAT_R8G8B8A8_UINT,
    DXGI_FORMAT_R8G8B8A8_SNORM,
    DXGI_FORMAT_R8G8B8A8_SINT,
    DXGI_FORMAT_R16G16_TYPELESS,
    DXGI_FORMAT_R16G16_FLOAT,
    DXGI_FORMAT_R16G16_UNORM,
    DXGI_FORMAT_R16G16_UINT,
    DXGI_FORMAT_R16G16_SNORM,
    DXGI_FORMAT_R16G16_SINT,
    DXGI_FORMAT_R32_TYPELESS,
    DXGI_FORMAT_D32_FLOAT,
    DXGI_FORMAT_R32_FLOAT,
    DXGI_FORMAT_R32_UINT,
    DXGI_FORMAT_R32_SINT,
    DXGI_FORMAT_R24G8_TYPELESS,
    DXGI_FORMAT_D24_UNORM_S8_UINT,
    DXGI_FORMAT_R24_UNORM_X8_TYPELESS,
    DXGI_FORMAT_X24_TYPELESS_G8_UINT,
    DXGI_FORMAT_R8G8_TYPELESS,
    DXGI_FORMAT_R8G8_UNORM,
    DXGI_FORMAT_R8G8_UINT,
    DXGI_FORMAT_R8G8_SNORM,
    DXGI_FORMAT_R8G8_SINT,
    DXGI_FORMAT_R16_TYPELESS,
    DXGI_FORMAT_R16_FLOAT,
    DXGI_FORMAT_D16_UNORM,
    DXGI_FORMAT_R16_UNORM,
    DXGI_FORMAT_R16_UINT,
    DXGI_FORMAT_R16_SNORM,
    DXGI_FORMAT_R16_SINT,
    DXGI_FORMAT_R8_TYPELESS,
    DXGI_FORMAT_R8_UNORM,
    DXGI_FORMAT_R8_UINT,
    DXGI_FORMAT_R8_SNORM,
    DXGI_FORMAT_R8_SINT,
    DXGI_FORMAT_A8_UNORM,
    DXGI_FORMAT_R1_UNORM,
    
};

/**
* @brief 텍스처 상태 구조체
*/
struct D3D11_TEXTURE_STATE
{
    NameHash Name; // 텍스처 이름 해시
    INT32 BindIndex; // 바인드 인덱스

    TEXTURE_TYPE TextureType; // 텍스처 타입
    UINT32 SamplerIndex; // 샘플러 인덱스

    union
    {
        ITexture1D* pTexture1D; // 1D 텍스처 포인터
        ITexture2D* pTexture2D; // 2D 텍스처 포인터
    };

};


class D3D11ConstantBuffer;

struct D3D11_CONSTANT_STATE
{
    NameHash Name; // 상수 버퍼 이름 해시
    INT32 BindIndex; // 바인드 인덱스
    D3D11ConstantBuffer* pCB; // 상수 버퍼 포인터

    constexpr D3D11_CONSTANT_STATE()
        : BindIndex(-1)
        , pCB(nullptr)
    {
    }
};

// 입력 레이아웃 생성 구조체
struct D3D11_INPUTLAYOUT_DESC
{
    UINT32 NumVertexFormat;
    UINT32 VertexFormat;
    VERTEX_FORMAT VertexFormats[MAX_VERTEX_FORMAT];
    ID3DBlob* pShaderBlob;
};

// 셰이더 컴파일 구조체
struct D3D11_SHADER_COMPILE_DESC
{
    char szShaderName[64];
    char szEntryPoint[64];
    char szShaderModel[32];
    char szShaderDefines[32][64];
    void* pBuffer;
    UINT32 BufferSize;
    UINT32 NumDefines;
    SHADER_TYPE ShaderType;
    BOOL Debug;
};

// 셰이더 파라미터 타입
enum D3D11_SHADER_PARAM_TYPE
{
	CPARAM_UNKNOWN,
    CPARAM_CONSTANT,
	CPARAM_TEXTURE,
	CPARAM_SAMPLER
};

// 셰이더 파라미터 정보 구조체
struct D3D11_SHADER_PARAMS
{
    D3D11_SHADER_PARAM_TYPE ParamType;
    NameHash Name;
	uint32 BindPoint;

    union
    {
        UINT32 Size;
        UINT32 Count;
    };
};

// 셰이더 컴파일 결과 구조체
constexpr size_t MAX_SHADER_PARAMS = 32;
struct D3D11_SHADER_COMPILE_RESULT
{
    ID3DBlob* pShaderBlob;
    D3D11_SHADER_PARAMS ShaderParams[MAX_SHADER_PARAMS];
    UINT32 NumShaderParams;
    UINT32 BufferFormat;
	UINT32 VertexFormats[MAX_VERTEX_FORMAT];
	UINT32 NumVertexFormat;
};

struct D3D11_TEXTURE1D_CREATE_DESC
{
	NameHash Name;
	UINT32 Width;
	UINT32 MipLevels;
	COLOR_FORMAT Format;
    RESOURCE_USAGE Usage;
    UINT32 InitialSize;
    void* pInitialData;
};

struct D3D11_TEXTURE2D_CREATE_DESC
{
    NameHash Name;
    UINT32 Width;
    UINT32 Height;
    UINT32 MipLevels;
    COLOR_FORMAT Format;
    RESOURCE_USAGE Usage;
    UINT32 InitialSize;
	void* pInitialData;
};

struct D3D11_RENDERTARGET_CREATE_DESC
{
    UINT32 ColorWidth;
    UINT32 ColorHeight;
    COLOR_FORMAT ColorFormat;

	BOOL CreateDepthStencil;
	UINT32 DepthWidth;
	UINT32 DepthHeight;
	COLOR_FORMAT DepthFormat;
};

static constexpr size_t POOL_BLOCK_TYPE_COUNT = 11;


#endif // __D3D11_RENDER_DEF_H__

